# Generated by Django 4.0.3 on 2022-09-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='nickname2',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
